# Generated by Django 2.2.13 on 2020-09-05 17:40

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200905_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='08050434674', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to=application.models.profile_image),
        ),
    ]
