# Generated by Django 2.2.13 on 2020-09-06 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_auto_20200905_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='can_donate_for_bookdrive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='idea_achieve_objectives',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='idea_funding',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='idea_project_successful',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='idea_promote_reading',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_experienced_writer',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='thoughts_writing_space',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deputy_team_lead', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='objectives',
            field=models.ManyToManyField(to='application.Objective'),
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(to='application.Team'),
        ),
    ]
