# Generated by Django 2.2.13 on 2020-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200906_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='thoughts_writing_space',
        ),
        migrations.AddField(
            model_name='member',
            name='thoughts_on_writing_space',
            field=models.CharField(choices=[('SA', 'Strongly Agree'), ('A', 'Agree'), ('N', 'Neutral'), ('D', 'Disagree'), ('SD', 'Strongly Disagree')], max_length=20, null=True),
        ),
    ]
