# Generated by Django 2.2.13 on 2020-09-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200906_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_experienced_writer',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=10, null=True),
        ),
    ]
